# Generated by Django 5.1 on 2024-09-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customuser_activation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('video', 'Videollamada'), ('in_person', 'Reunión presencial')], max_length=10)),
                ('location', models.CharField(choices=[('lugar1', 'Lugar 1'), ('lugar2', 'Lugar 2')], max_length=10)),
                ('additional_message', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('deposit', 'Depósito bancario'), ('cash', 'Efectivo')], max_length=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
